name: 🚀 Deploy website on push to main

# Trigger the workflow on push and 
# pull request events on the main branch
on:
  push:
    branches:
      - main
      
# Authenticate to the the server via FTP 
# and run the deployment script 
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Create env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run prod
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
